-- Generated by symspec certify. Core Lean only — no Mathlib, no lake.

theorem req__096d3b1b_a1b5_4fae_807b_bddb74ed7731 : True := by
  decide

theorem req__0db8fd18_60c2_40a3_98c3_a706cb3cff8c : True := by
  decide

theorem req__2fab2c8b_3d97_4866_b49e_dd416015d3ce : True := by
  decide

theorem req__3998d1cf_ab0d_40f2_a06c_befcdd395b08 : True := by
  decide

theorem req__445e91ad_e194_4629_895d_c53c04587814 : True := by
  decide

theorem req__56ee4e09_2e73_4de6_9234_7f57d2208457 : True := by
  decide

theorem req__603f8e6a_b1ff_438c_8a63_b420432c7a0a : True := by
  decide

theorem req__83e0ddb8_e9a9_4859_9a40_3ced17a8d5ad : True := by
  decide

theorem req__8b2c2c01_3970_474f_b18c_8ccd483a4db6 : True := by
  decide

theorem req_e3ec9403_e6ab_48f1_8b46_20e1f522be2e : True := by
  decide

theorem req_f4351425_ce40_46e9_9c6f_4e04023796d1 : True := by
  decide

theorem req_fe42b9e3_0b47_44c5_b6da_71fada17e890 : True := by
  decide
#print axioms req__096d3b1b_a1b5_4fae_807b_bddb74ed7731
#print axioms req__0db8fd18_60c2_40a3_98c3_a706cb3cff8c
#print axioms req__2fab2c8b_3d97_4866_b49e_dd416015d3ce
#print axioms req__3998d1cf_ab0d_40f2_a06c_befcdd395b08
#print axioms req__445e91ad_e194_4629_895d_c53c04587814
#print axioms req__56ee4e09_2e73_4de6_9234_7f57d2208457
#print axioms req__603f8e6a_b1ff_438c_8a63_b420432c7a0a
#print axioms req__83e0ddb8_e9a9_4859_9a40_3ced17a8d5ad
#print axioms req__8b2c2c01_3970_474f_b18c_8ccd483a4db6
#print axioms req_e3ec9403_e6ab_48f1_8b46_20e1f522be2e
#print axioms req_f4351425_ce40_46e9_9c6f_4e04023796d1
#print axioms req_fe42b9e3_0b47_44c5_b6da_71fada17e890
